/**
 * E2E tests for `cmc generate` command
 */

import { describe, it, expect } from 'vitest';
import { runInDocker } from './docker-runner.js';
import { dockerAvailable, images, setupImages } from './setup.js';

// Setup: Build required images (only need typescript for generate tests)
setupImages(['typescript']);

// =============================================================================
// Generate: ESLint config
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate eslint', () => {
  it('generates valid ESLint config with --stdout', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'eslint', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('// Generated by cmc (check-my-code)');
    expect(result.stdout).toContain("import js from '@eslint/js'");
    expect(result.stdout).toContain('tseslint.config(');
  }, 30000);

  it('includes rules from cmc.toml', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'eslint', '--stdout']);

    expect(result.stdout).toContain('"no-var": "error"');
    expect(result.stdout).toContain('"prefer-const": "error"');
    expect(result.stdout).toContain('"eqeqeq"');
  }, 30000);

  it('writes file and reports success', async () => {
    // Note: This modifies the container filesystem (ephemeral)
    const result = await runInDocker(images['typescript'], ['generate', 'eslint', '--force']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Generated eslint.config.js');
  }, 30000);
});

// =============================================================================
// Generate: Ruff config
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate ruff', () => {
  it('generates valid Ruff config with --stdout', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'ruff', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('# Generated by cmc (check-my-code)');
    expect(result.stdout).toContain('line-length = 100');
    expect(result.stdout).toContain('[lint]');
  }, 30000);

  it('includes lint rules from cmc.toml', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'ruff', '--stdout']);

    expect(result.stdout).toContain('select = ["E","F","I"]');
    expect(result.stdout).toContain('ignore = ["E501"]');
  }, 30000);
});

// =============================================================================
// Generate: Error handling
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate - error handling', () => {
  it('fails with exit code 3 for unknown linter', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'unknown']);

    expect(result.exitCode).toBe(3);
    expect(result.stderr).toContain('Unknown linter');
  }, 30000);

  it('is case insensitive for linter name', async () => {
    const result = await runInDocker(images['typescript'], ['generate', 'ESLINT', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('// Generated by cmc');
  }, 30000);
});
