import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { isDockerAvailable, cleanupImages, buildImage, runInDocker } from './docker-runner.js';

// Check Docker availability synchronously at module load
const dockerAvailable = await isDockerAvailable();

if (!dockerAvailable) {
  console.warn('Docker not available - skipping Docker-based e2e tests');
}

// =============================================================================
// Build images once upfront for performance
// =============================================================================
const images: Record<string, string> = {};

beforeAll(async () => {
  if (!dockerAvailable) return;

  const projectNames = ['generate-test', 'generate-existing', 'generate-no-config'];

  const results = await Promise.all(projectNames.map((name) => buildImage(name)));

  projectNames.forEach((name, i) => {
    images[name] = results[i];
  });
}, 300000); // 5 min timeout for all builds

afterAll(async () => {
  if (dockerAvailable) {
    await cleanupImages(Object.values(images));
  }
}, 30000);

// =============================================================================
// Generate command - ESLint config generation
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate eslint', () => {
  it('generates eslint.config.js with --stdout', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'eslint', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('// Generated by cmc (check-my-code)');
    expect(result.stdout).toContain("import js from '@eslint/js'");
    expect(result.stdout).toContain("import tseslint from 'typescript-eslint'");
    expect(result.stdout).toContain('tseslint.config(');
  }, 30000);

  it('includes rules from cmc.toml in generated config', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'eslint', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('"no-var": "error"');
    expect(result.stdout).toContain('"prefer-const": "error"');
    expect(result.stdout).toContain('"eqeqeq"');
  }, 30000);

  it('writes eslint.config.js file', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'eslint']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Generated eslint.config.js');
  }, 30000);

  it('fails when eslint.config.js already exists', async () => {
    const result = await runInDocker(images['generate-existing'], ['generate', 'eslint']);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain('eslint.config.js already exists');
    expect(result.stderr).toContain('--force');
  }, 30000);

  it('overwrites existing config with --force', async () => {
    const result = await runInDocker(images['generate-existing'], [
      'generate',
      'eslint',
      '--force',
    ]);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Generated eslint.config.js');
  }, 30000);
});

// =============================================================================
// Generate command - Ruff config generation
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate ruff', () => {
  it('generates ruff.toml with --stdout', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'ruff', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('# Generated by cmc (check-my-code)');
    expect(result.stdout).toContain('line-length = 100');
    expect(result.stdout).toContain('[lint]');
  }, 30000);

  it('includes lint rules from cmc.toml', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'ruff', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('select = ["E","F","I"]');
    expect(result.stdout).toContain('ignore = ["E501"]');
  }, 30000);

  it('writes ruff.toml file', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'ruff']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Generated ruff.toml');
  }, 30000);
});

// =============================================================================
// Generate command - Error handling
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate error handling', () => {
  it('fails with exit code 2 when cmc.toml missing', async () => {
    const result = await runInDocker(images['generate-no-config'], ['generate', 'eslint']);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain('No cmc.toml found');
  }, 30000);

  it('fails with exit code 3 for unknown linter', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'unknown']);

    expect(result.exitCode).toBe(3);
    expect(result.stderr).toContain('Unknown linter');
    expect(result.stderr).toContain('eslint, ruff');
  }, 30000);

  it('is case insensitive for linter name', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', 'ESLINT', '--stdout']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('// Generated by cmc');
  }, 30000);
});

// =============================================================================
// Generate command - Help
// =============================================================================
describe.skipIf(!dockerAvailable)('cmc generate --help', () => {
  it('shows usage information', async () => {
    const result = await runInDocker(images['generate-test'], ['generate', '--help']);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('Usage:');
    expect(result.stdout).toContain('generate');
    expect(result.stdout).toContain('--force');
    expect(result.stdout).toContain('--stdout');
  }, 30000);
});
